### ISSUE TITLE
Doesn't work with LTS

### ISSUE THREAD

**Issue by crbreingan** [FrontEndART/SonarQube-plug-in#6]
This plugin does not work with the latest LTS version of SonarQube (v5.6.6).

I got the following error in the sonar.log:

```
2017.08.16 18:14:10 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
org.sonar.api.utils.SonarException: FrontEndART SourceMeter plugin does not support your SonarQube server version (5.6.6). For more information about the supported versions, check http://www.frontendart.com/ or read the documention of the plugin.
	at com.sourcemeter.analyzer.java.core.VersionChecker.onServerStart(VersionChecker.java:43) ~[na:na]
	at org.sonar.server.platform.ServerLifecycleNotifier.notifyStart(ServerLifecycleNotifier.java:67) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:82) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:44) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:77) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:201) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.platform.Platform.doStart(Platform.java:114) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.platform.Platform.doStart(Platform.java:99) ~[sonar-server-5.6.6.jar:na]
	at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:44) ~[sonar-server-5.6.6.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_131]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]
```

I understand the purpose of the version checker, but perhaps it may be better to make a warning instead of causing SonarQube to fail. Who knows, maybe SourceMeter still works with the latest SonarQube. It would be worth a shot if the Version checker didn't cause SonarQube to crash.

**Comment by crbreingan** [comment]
It does not just work by updating the version checker... 

```
2017.08.16 19:10:00 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.RubyRailsContextListener
org.jruby.rack.RackInitializationException: uninitialized constant SourcemeterDuplicationsController::SourceHelper
	from C:/sonarqube-5.6.6/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:131:in `const_missing'
	from C:/sonarqube-5.6.6/temp/ror/SourceMeterGUI/app/controllers/sourcemeter_duplications_controller.rb:21:in `SourcemeterDuplicationsController'
	from C:/sonarqube-5.6.6/temp/ror/SourceMeterGUI/app/controllers/sourcemeter_duplications_controller.rb:20:in `(root)'
	from org/jruby/RubyKernel.java:1075:in `require'
	from jar:file:/C:/sonarqube-5.6.6/lib/server/jruby-complete-1.7.9.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require'
	from jar:file:/C:/sonarqube-5.6.6/lib/server/jruby-complete-1.7.9.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require'
	from C:/sonarqube-5.6.6/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:184:in `require'
	from C:/sonarqube-5.6.6/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:291:in `require_or_load'
	from C:/sonarqube-5.6.6/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:250:in `depend_on'
	from C:/sonarqube-5.6.6/web/WEB-INF/gems/gems/activesupport-2.3.15/lib/active_support/dependencies.rb:162:in `require_dependency'
	from C:/sonarqube-5.6.6/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:1:in `(root)'
	from org/jruby/RubyArray.java:1613:in `each'
	from C:/sonarqube-5.6.6/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:414:in `load_application_classes'
	from org/jruby/RubyArray.java:1613:in `each'
	from C:/sonarqube-5.6.6/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:413:in `load_application_classes'
	from C:/sonarqube-5.6.6/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:411:in `load_application_classes'
	from org/jruby/RubyKernel.java:2223:in `send'
	from C:/sonarqube-5.6.6/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:197:in `process'
	from C:/sonarqube-5.6.6/web/WEB-INF/gems/gems/rails-2.3.15/lib/initializer.rb:113:in `run'
	from org/jruby/RubyKernel.java:1094:in `load'
	from C:/sonarqube-5.6.6/web/WEB-INF/config/environment.rb:86:in `(root)'
	from file:/C:/sonarqube-5.6.6/lib/server/jruby-rack-1.1.13.2.jar!/jruby/rack/rails/environment2.rb:1:in `(root)'
	from file:/C:/sonarqube-5.6.6/lib/server/jruby-rack-1.1.13.2.jar!/jruby/rack/rails/environment2.rb:25:in `load_environment'
...
```

**Comment by pille5** [comment]
@crbreingan thanks for your bug report. The SourceMeter plugins only support the (previous LTS) 4.5.x versions. There were too many major changes in the SQ, so the update is not trivial. We are working on the update to the latest (6.3) API. We'll deploy it when it's ready. Stay tuned. :)
